export const SITE = {
  name: 'Redline Roofing & Restoration',
  legalName: 'Redline Roofing & Restoration, LLC',
  tagline: 'The last roof you\'ll ever buy. Built by Oklahomans, backed for life.',
  phone: '(928) 628-6080',
  phoneHref: 'tel:+19286286080',
  email: 'hello@redlineroofingok.com',
  address: {
    street: '2401 NW 23rd Street, Suite 300',
    city: 'Oklahoma City',
    state: 'OK',
    zip: '73107',
  },
  geo: {
    lat: 35.4895,
    lng: -97.5316,
  },
  founded: 2007,
  hours: 'Mon–Fri 7a–6p, Sat 8a–2p, Sun closed (24/7 storm response)',
  socials: {
    facebook: 'https://www.facebook.com/redlineroofingok',
    instagram: 'https://www.instagram.com/redlineroofingok',
    linkedin: 'https://www.linkedin.com/company/redline-roofing-restoration',
    google: 'https://www.google.com/maps?cid=PLACEHOLDER_CID',
  },
  url: 'https://redlineroofingok.com',
  cibLicense: '80003217',
  certs: [
    'GAF Master Elite',
    'Owens Corning Platinum Preferred',
    'CertainTeed SELECT ShingleMaster',
    'Malarkey Emerald Premium',
    'BBB A+',
    'Google Guaranteed',
  ],
  ownerName: 'Travis "Trey" McAllister III',
  ownerTitle: 'Founder & President',
  serviceAreas: [
    { slug: 'oklahoma-city', name: 'Oklahoma City', county: 'Oklahoma County', zip: '73101-73199', note: 'Headquarters — 2401 NW 23rd Street' },
    { slug: 'edmond', name: 'Edmond', county: 'Oklahoma County', zip: '73003, 73012, 73013, 73034', note: 'North OKC metro, frequent large-hail corridor' },
    { slug: 'norman', name: 'Norman', county: 'Cleveland County', zip: '73019, 73026, 73069, 73071, 73072', note: 'University of Oklahoma, south metro' },
    { slug: 'moore', name: 'Moore', county: 'Cleveland County', zip: '73153, 73160, 73170', note: 'Tornado Alley epicenter, major rebuilds post-2013' },
    { slug: 'yukon', name: 'Yukon', county: 'Canadian County', zip: '73085, 73099', note: 'West metro, Route 66 corridor' },
    { slug: 'mustang', name: 'Mustang', county: 'Canadian County', zip: '73064', note: 'Fast-growing southwest suburb' },
    { slug: 'bethany', name: 'Bethany', county: 'Oklahoma County', zip: '73008', note: 'Inner west suburb, older housing stock' },
    { slug: 'midwest-city', name: 'Midwest City', county: 'Oklahoma County', zip: '73110, 73130', note: 'Adjacent to Tinker AFB, military families' },
    { slug: 'del-city', name: 'Del City', county: 'Oklahoma County', zip: '73115, 73135', note: 'Southeast metro, post-war housing' },
    { slug: 'piedmont', name: 'Piedmont', county: 'Canadian County', zip: '73078', note: 'Rural-suburban northwest, acreage properties' },
    { slug: 'choctaw', name: 'Choctaw', county: 'Oklahoma County', zip: '73020', note: 'East metro, rural residential' },
    { slug: 'newcastle', name: 'Newcastle', county: 'McClain County', zip: '73065', note: 'South metro growth corridor' },
    { slug: 'nichols-hills', name: 'Nichols Hills', county: 'Oklahoma County', zip: '73116, 73120', note: 'Affluent enclave, steep complex rooflines' },
    { slug: 'the-village', name: 'The Village', county: 'Oklahoma County', zip: '73120', note: 'Central OKC suburb, mid-century homes' },
  ],
} as const;

export type ServiceArea = (typeof SITE.serviceAreas)[number];
